name: youtube-downloader

services:
    server:
        user: "${UID:-1000}:${GID:-1000}"
        image: registry.florian-dev.fr:443/floriantrayon/youtube-downloader:${VERSION:-latest}
        command: apache2-foreground
        restart: unless-stopped
        volumes:
            - ./output:/var/www/html/output
        healthcheck:
            test: curl -f http://localhost
            retries: 3
            timeout: 5s
        build:
            target: production
            context: .
            dockerfile: docker/Dockerfile
        ports:
            - "${PORT:-80}:80"