name: youtube-downloader

services:
    server:
        image: youtube-downloader
        command: apache2-foreground
        volumes:
            - .:/var/www/html
        extra_hosts:
            - "host.docker.internal:host-gateway"
        healthcheck:
            test: curl -f http://localhost
            retries: 3
            timeout: 5s
            start_period: 30s
        build:
            target: development
            context: .
            dockerfile: docker/Dockerfile
        ports:
            - "80:80"