name: youtube-downloader

services:
    # https://github.com/FlorianLeChat/YouTube-Downloader
    php:
        image: youtube-downloader
        volumes:
            - .:/var/www/html
        command: ./docker/scripts/development/entrypoint.sh
        healthcheck:
            test: curl -f http://localhost
            retries: 3
            timeout: 5s
        build:
            context: .
            dockerfile: ./docker/scripts/development/Dockerfile
        ports:
            - "80:80"