name: youtube-downloader

services:
    # https://github.com/FlorianLeChat/YouTube-Downloader
    php:
        image: youtube-downloader
        restart: always
        healthcheck:
            test: curl -f http://127.0.0.1:9000/ 2>&1 | grep "Connection reset by peer"
            retries: 3
            timeout: 5s
        build:
            context: .
            dockerfile: ./docker/scripts/production/Dockerfile
        ports:
            - "9000:9000"