name: youtube-downloader

services:
    # https://github.com/FlorianLeChat/YouTube-Downloader
    php:
        image: youtube-downloader
        command: ./docker/scripts/development/entrypoint.sh
        develop:
            watch:
                - path: .
                  action: sync
                  target: /var/www/html
                - path: composer.lock
                  action: rebuild
        healthcheck:
            test: curl -f http://localhost
            retries: 3
            timeout: 5s
        build:
            context: .
            dockerfile: ./docker/scripts/development/Dockerfile
        ports:
            - "80:80"