version: "3.9"

services:
  # https://github.com/FlorianLeChat/YouTube-Downloader
  php-nginx:
    image: youtubedownloader
    container_name: website
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PHP_VERSION: 8.2
    ports:
      - 80:80