name: youtube-downloader

version: "3.8"

services:
    # https://github.com/FlorianLeChat/YouTube-Downloader
    php:
        image: youtube-downloader
        restart: always
        volumes:
            - ./output:/var/www/html/output
            - ./output/temp:/var/www/html/output/temp
        healthcheck:
            test: curl -f http://127.0.0.1:9000/ 2>&1 | grep "Connection reset by peer" || curl -f http://localhost
            retries: 3
            timeout: 5s
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: 128M
                reservations:
                    cpus: "0.25"
                    memory: 32M
        build:
            args:
                - VERSION
                - MANAGER
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 80:80