# syntax=docker/dockerfile:1

# Use an customized image of PHP
# https://hub.docker.com/_/php
FROM php:apache

# Install dependencies
RUN apt update && apt install python3 python3-pip ffmpeg -y

# Install yt-dl (patched version)
RUN python3 -m pip install --break-system-packages https://github.com/yt-dlp/yt-dlp/archive/master.tar.gz

# Install some PHP extensions
RUN curl -sSLf -o /usr/local/bin/install-php-extensions \
		https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions && \
	chmod +x /usr/local/bin/install-php-extensions && \
	install-php-extensions zip opcache

# Set the working directory to the website files
WORKDIR /var/www/html

# Install Composer for dependency management
COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

# Copy all files to the working directory
COPY --chown=www-data:www-data . .

# Use the default or custom PHP configuration (if exists)
RUN mv $PHP_INI_DIR/php.ini-production $PHP_INI_DIR/php.ini && \
	if [ -f "docker/php.ini" ]; then \
		mv "docker/php.ini" "$PHP_INI_DIR/php.ini"; \
	fi

# Change current user to www-data
USER www-data

# Install all dependencies
# Use cache mount to speed up installation of existing dependencies
RUN --mount=type=cache,target=.composer composer install